### ISSUE TITLE
I may be missing something

### ISSUE THREAD

**Issue by datermine** [jbochi/gifstreaming#6]
1) ffmpeg -i vid.mp4 -loop 1 -pix_fmt pal8 -s 159x97 -r 10 "input/in%d.gif"

This results in a gif named: in%d.gif in input/

2) Run: python transform.py

This results in:

$ python transform.py 
Finding new files...
Traceback (most recent call last):
  File "transform.py", line 110, in <module>
    transform()
  File "transform.py", line 89, in transform
    os.path.join(OUTPUT_PATH, "0.part"))
  File "transform.py", line 75, in create_header_file
    with open(input_path, "rb") as f:
IOError: [Errno 2] No such file or directory: 'input/in1.gif'

What am I missing?

**Comment by jbochi** [comment]
Could you please provide the OS and Python version that you are using?

**Comment by datermine** [comment]
> > > import sys
> > > print sys.version
> > > 2.7.2 (default, Oct 11 2012, 20:14:37) 
> > > [GCC 4.2.1 Compatible Apple Clang 4.0 (tags/Apple/clang-418.0.60)]

Mac OSX 10.8.4

I guess what I don't understand is (and I could probably look up the documentation to ffmpeg to figure this out):
- Is the output of the ffmpeg command 1 gif named "in%d.gif"?
- What's the expected output from the transform command? 

Thanks in advance.

**Comment by dipankar** [comment]
The problem is with the version of ffmpeg, you will need to user 1.2.3 and not the latest version. There is an open bug where generation of single gif files is broken.

**Comment by jbochi** [comment]
Sorry for the late reply. @dipankar is right (thanks!). ffmpeg was supposed to create a file name `input/in1.gif`.

**Comment by cyphunk** [comment]
having a similar issue on Linux with ffmpeg 2.8. Does anyone know if there is a pkg for version 1.2.3 or another work around other than compiling the older version?

**Comment by cyphunk** [comment]
I found a resolution at https://stackoverflow.com/questions/18526619/ffmpeg-save-separate-frames-as-still-gifs. Execute as:

``ffmpeg -re -i <stream> -pix_fmt pal8 -s 159x97 -r 10 -f image2 input/in%d.gif``
